# Generated by Django 5.2 on 2025-06-07 16:53

import customer.models
import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(error_messages={'max_length': 'El nombre no puede exceder los 100 caracteres.', 'required': 'El nombre es un campo obligatorio.'}, help_text='Nombres del cliente (máx. 100 caracteres).', max_length=100, verbose_name='nombres')),
                ('last_name', models.CharField(error_messages={'max_length': 'El apellido no puede exceder los 100 caracteres.', 'required': 'El apellido es un campo obligatorio.'}, help_text='Apellidos del cliente (máx. 100 caracteres).', max_length=100, verbose_name='apellidos')),
                ('document_type', models.CharField(choices=[('DUI', 'DUI'), ('Pasaporte', 'Pasaporte')], error_messages={'invalid_choice': 'El tipo de documento seleccionado no es válido.', 'required': 'Debe seleccionar un tipo de documento.'}, help_text='Seleccione el tipo de documento de identificación.', max_length=10, verbose_name='tipo de documento')),
                ('document_number', models.CharField(error_messages={'required': 'El número de documento es obligatorio.', 'unique': 'Este número de documento ya está registrado con este tipo de documento.'}, help_text='Número del documento de identificación (DUI o Pasaporte).', max_length=50, verbose_name='número de documento')),
                ('address', models.TextField(error_messages={'required': 'La dirección es obligatoria.'}, help_text='Dirección de residencia del cliente.', verbose_name='dirección')),
                ('phone', models.CharField(error_messages={'required': 'El número de teléfono es obligatorio.'}, help_text='Número de teléfono de contacto. Formato para El Salvador: 1234-5678.', max_length=20, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe tener un formato válido (ej. 7777-7777 o +50377777777).', regex='^\\+?1?\\d{8,15}$')], verbose_name='teléfono')),
                ('email', models.EmailField(error_messages={'required': 'El correo electrónico es obligatorio.', 'unique': 'Este correo electrónico ya está registrado.'}, help_text='Correo electrónico único del cliente.', max_length=100, unique=True, verbose_name='correo electrónico')),
                ('customer_type', models.CharField(choices=[('Nacional', 'Nacional'), ('Extranjero', 'Extranjero')], error_messages={'required': 'Debe seleccionar el tipo de cliente.'}, help_text='Indique si el cliente es nacional o extranjero.', max_length=10, verbose_name='tipo de cliente')),
                ('birth_date', models.DateField(error_messages={'invalid': 'Ingrese una fecha válida.', 'required': 'La fecha de nacimiento es obligatoria.'}, help_text='El cliente debe ser mayor de 18 años.', validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(1900, 1, 1), message='La fecha de nacimiento no puede ser anterior a 1900.'), customer.models.validate_birth_date], verbose_name='fecha de nacimiento')),
                ('status', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Lista Negra', 'Lista Negra')], default='Activo', help_text='Estado actual del cliente en el sistema.', max_length=20, verbose_name='estado del cliente')),
                ('reference', models.CharField(blank=True, help_text='Contacto de referencia del cliente (opcional).', max_length=100, null=True, verbose_name='referencia')),
                ('notes', models.TextField(blank=True, help_text='Cualquier nota relevante sobre el cliente (opcional).', null=True, verbose_name='notas adicionales')),
                ('active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_by', models.IntegerField(blank=True, null=True, verbose_name='creado por')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('modified_by', models.IntegerField(blank=True, null=True, verbose_name='modificado por')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última modificación')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'customer',
                'unique_together': {('document_type', 'document_number')},
            },
        ),
    ]
