# Generated by Django 5.2 on 2025-06-07 16:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_name', models.CharField(error_messages={'unique': 'Ya existe una empresa con este nombre comercial.'}, help_text='Nombre comercial de la empresa.', max_length=100, unique=True, verbose_name='nombre comercial')),
                ('nrc', models.CharField(error_messages={'unique': 'Este NRC ya está registrado.'}, help_text='Número de Registro de Contribuyente (ej. 12345-6).', max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='El formato del NRC debe ser, por ejemplo, 12345-6.', regex='^\\d{1,6}-\\d{1}$')], verbose_name='NRC (Número de Registro de Contribuyente)')),
                ('classification', models.CharField(choices=[('Pequeña', 'Pequeña'), ('Mediana', 'Mediana'), ('Gran', 'Gran Contribuyente')], help_text='Clasificación de la empresa según su tamaño o tipo de contribuyente.', max_length=20, verbose_name='clasificación')),
                ('phone', models.CharField(help_text='Número de teléfono de contacto de la empresa.', max_length=20, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe tener un formato válido.', regex='^\\+?1?\\d{8,15}$')], verbose_name='teléfono de la empresa')),
                ('address', models.TextField(help_text='Dirección fiscal o principal de la empresa.', verbose_name='dirección fiscal')),
                ('logo', models.CharField(blank=True, help_text="Logotipo de la empresa. Se guardará en la carpeta 'company_logos'.", max_length=100, null=True, verbose_name='logotipo')),
                ('email', models.EmailField(error_messages={'unique': 'Este correo electrónico ya está registrado.'}, help_text='Correo electrónico principal de la empresa.', max_length=100, unique=True, verbose_name='correo electrónico de la empresa')),
                ('website', models.URLField(blank=True, help_text='Página web de la empresa (opcional).', max_length=100, null=True, verbose_name='sitio web')),
                ('active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_by', models.IntegerField(blank=True, null=True, verbose_name='creado por')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('modified_by', models.IntegerField(blank=True, null=True, verbose_name='modificado por')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última modificación')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresa',
                'db_table': 'company',
            },
        ),
    ]
