# Generated by Django 5.2 on 2025-06-10 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo_lqip',
            field=models.URLField(blank=True, help_text='URL de la imagen de baja calidad para carga rápida.', max_length=255, null=True, verbose_name='Logo de Baja Calidad (LQIP)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logotipo de la empresa.', null=True, upload_to='company_logos/', verbose_name='Logotipo'),
        ),
    ]
