# Generated by Django 5.2 on 2025-06-11 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_company_logo_lqip_alter_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo_public_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cloudinary Public ID del Logo'),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='URL del Logotipo'),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo_lqip',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Logo de Baja Calidad (LQIP)'),
        ),
    ]
