# Generated by Django 5.2 on 2025-05-09 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_helper', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalProxyUser',
        ),
    ]
