# Generated by Django 5.2 on 2025-05-09 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_helper', '0002_delete_historicalproxyuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProxyUser',
        ),
    ]
