# Generated by Django 5.2 on 2025-06-04 20:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('municipality', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='municipality',
            options={'ordering': ['department', 'municipality'], 'verbose_name': 'Municipio', 'verbose_name_plural': 'Municipios'},
        ),
        migrations.AlterField(
            model_name='municipality',
            name='code',
            field=models.CharField(error_messages={'unique': 'Ya existe un municipio con este código.'}, help_text='Código numérico único de hasta 8 dígitos para el municipio.', max_length=8, unique=True, validators=[django.core.validators.RegexValidator(message='El código de municipio solo puede contener números.', regex='^[0-9]+$')], verbose_name='código de municipio'),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='created_by',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID del creador'),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='modified_by',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID del modificador'),
        ),
    ]
