# Generated by Django 5.2 on 2025-04-23 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_control', '0002_historicalusersmetadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalusersmetadata',
            name='user_image',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usersmetadata',
            name='user_image',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
