# Generated by Django 5.2 on 2025-06-06 00:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('municipality', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(error_messages={'unique': 'Ya existe un distrito con este código.'}, help_text='Código numérico único de hasta 8 dígitos para el distrito.', max_length=8, unique=True, validators=[django.core.validators.RegexValidator(message='El código de distrito solo puede contener números.', regex='^[0-9]+$')], verbose_name='código de distrito')),
                ('district', models.CharField(error_messages={'blank': 'El nombre del distrito no puede estar vacío.', 'required': 'El nombre del distrito es obligatorio.'}, help_text="Nombre oficial del distrito. Solo se permiten letras, números, espacios y los caracteres: - . , # & ( ) '", max_length=255, validators=[django.core.validators.RegexValidator(message="El nombre del distrito solo puede contener letras, números, espacios y los siguientes caracteres especiales: - . , # & ( ) '", regex="^[a-zA-Z0-9\\s\\-\\.,#&()\\'ñÑáéíóúÁÉÍÓÚ]+$")], verbose_name='nombre del distrito')),
                ('active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_by', models.IntegerField(blank=True, null=True, verbose_name='ID del creador')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('modified_by', models.IntegerField(blank=True, null=True, verbose_name='ID del modificador')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última modificación')),
                ('municipality', models.ForeignKey(error_messages={'invalid_choice': 'El municipio seleccionado no es válido.', 'required': 'Debe seleccionar un municipio.'}, help_text='Municipio al que está asociado este distrito.', on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='municipality.municipality', verbose_name='municipio al que pertenece')),
            ],
            options={
                'verbose_name': 'Distrito',
                'verbose_name_plural': 'Distritos',
                'db_table': 'district',
                'ordering': ['municipality', 'district'],
            },
        ),
    ]
