# Generated by Django 5.2 on 2025-05-31 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='district',
            table='district',
        ),
    ]
