# Generated by Django 5.2 on 2025-06-04 20:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0002_alter_district_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='district',
            options={'ordering': ['municipality', 'district'], 'verbose_name': 'Distrito', 'verbose_name_plural': 'Distritos'},
        ),
        migrations.AlterField(
            model_name='district',
            name='code',
            field=models.CharField(error_messages={'unique': 'Ya existe un distrito con este código.'}, help_text='Código numérico único de hasta 8 dígitos para el distrito.', max_length=8, unique=True, validators=[django.core.validators.RegexValidator(message='El código de distrito solo puede contener números.', regex='^[0-9]+$')], verbose_name='código de distrito'),
        ),
        migrations.AlterField(
            model_name='district',
            name='created_by',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID del creador'),
        ),
        migrations.AlterField(
            model_name='district',
            name='modified_by',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID del modificador'),
        ),
    ]
