# Generated by Django 5.2 on 2025-06-06 00:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(error_messages={'unique': 'Ya existe un departamento con este código.'}, help_text='Código numérico único de hasta 8 dígitos para el departamento.', max_length=8, unique=True, validators=[django.core.validators.RegexValidator(message='El código solo puede contener números.', regex='^[0-9]+$')], verbose_name='código de departamento')),
                ('department', models.CharField(error_messages={'blank': 'El nombre del departamento no puede estar vacío.', 'required': 'El nombre del departamento es obligatorio.'}, help_text="Nombre oficial del departamento. Solo se permiten letras, números, espacios y los caracteres: - . , # & ( ) '", max_length=255, validators=[django.core.validators.RegexValidator(message="El nombre del departamento solo puede contener letras, números, espacios y los siguientes caracteres especiales: - . , # & ( ) '", regex="^[a-zA-Z0-9\\s\\-\\.,#&()\\'ñÑáéíóúÁÉÍÓÚ]+$")], verbose_name='nombre del departamento')),
                ('active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_by', models.IntegerField(blank=True, null=True, verbose_name='ID del creador')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('modified_by', models.IntegerField(blank=True, null=True, verbose_name='ID del modificador')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última modificación')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'db_table': 'department',
            },
        ),
    ]
