# Generated by Django 5.2 on 2025-05-31 00:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(error_messages={'unique': 'Ya existe un departamento con este código.'}, help_text='Código numérico único de hasta 8 dígitos para el departamento.', max_length=8, unique=True, validators=[django.core.validators.RegexValidator(message='El código solo puede contener números.', regex='^[0-9]+$')], verbose_name='código de departamento'),
        ),
        migrations.AlterField(
            model_name='department',
            name='created_by',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID del creador'),
        ),
        migrations.AlterField(
            model_name='department',
            name='modified_by',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID del modificador'),
        ),
    ]
