# Generated by Django 5.2 on 2025-05-16 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehiclecategory', '0001_initial'),
        ('vehiclemodel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=50)),
                ('year', models.PositiveIntegerField()),
                ('engine', models.CharField(max_length=100)),
                ('engine_type', models.CharField(max_length=100)),
                ('engine_number', models.CharField(max_length=100)),
                ('vin', models.CharField(max_length=100)),
                ('seat_count', models.IntegerField()),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Disponible', 'Disponible'), ('En mantenimiento', 'En mantenimiento'), ('En reparacion', 'En reparacion'), ('Reservado', 'Reservado'), ('Alquilado', 'Alquilado')], max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle_category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='vehiclecategory.vehiclecategory')),
                ('vehicle_model', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='vehiclemodel.vehiclemodel')),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
                'db_table': 'vehicle',
            },
        ),
    ]
