# Generated by Django 5.2 on 2025-05-16 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='vehicle_category',
            new_name='vehiclecategory',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='vehicle_model',
            new_name='vehiclemodel',
        ),
    ]
