# Generated by Django 5.2 on 2025-05-20 16:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_rename_vehicle_category_vehicle_vehiclecategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='engine',
            field=models.CharField(blank=True, help_text='Modelo o cilindrada del motor (p. ej. ‘2GR-FE’ o ‘1998’).', max_length=30),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='engine_number',
            field=models.CharField(help_text='Número de serie grabado en el bloque del motor.', max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='engine_type',
            field=models.CharField(choices=[('Gasolina', 'Gasolina'), ('Diesel', 'Diesel'), ('Electrico', 'Electrico'), ('Hibrido', 'Hibrido'), ('GLP', 'GLP')], help_text='Tipo de motor.', max_length=10),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='plate',
            field=models.CharField(help_text='Placa sin espacios, 6–8 caracteres (ej. ABC1234).', max_length=8, unique=True, validators=[django.core.validators.RegexValidator(message='La placa debe tener entre 6 y 8 caracteres alfanuméricos en mayúsculas.', regex='^[A-Z0-9]{6,8}$')]),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='seat_count',
            field=models.PositiveIntegerField(help_text='Número de asientos.'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('En mantenimiento', 'En mantenimiento'), ('En reparacion', 'En reparación'), ('Reservado', 'Reservado'), ('Alquilado', 'Alquilado')], max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vin',
            field=models.CharField(help_text='Vehicle Identification Number (17 caracteres).', max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message='VIN inválido: 17 caracteres sin I, O, Q.', regex='^[A-HJ-NPR-Z0-9]{17}$')]),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='year',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1886), django.core.validators.MaxValueValidator(2026, message='El año no puede ser mayor al siguiente año.')]),
        ),
    ]
