# Generated by Django 5.2 on 2025-05-22 01:30

import django.core.validators
import django.db.models.deletion
import vehicle.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0003_alter_vehicle_description_alter_vehicle_engine_and_more'),
        ('vehiclecategory', '0001_initial'),
        ('vehiclemodel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={'verbose_name': 'Vehículo', 'verbose_name_plural': 'Vehículos'},
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='active',
            field=models.BooleanField(default=True, verbose_name='activo'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='color',
            field=models.CharField(error_messages={'max_length': 'El color no puede tener más de 50 caracteres.', 'required': 'El color del vehículo es obligatorio.'}, help_text='Color del vehículo (máx. 50 caracteres).', max_length=50, validators=[django.core.validators.RegexValidator(message='El color solo debe contener letras y espacios.', regex='^[a-zA-Z\\s]+$')], verbose_name='color'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='created_by',
            field=models.IntegerField(blank=True, null=True, verbose_name='creado por'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='description',
            field=models.TextField(blank=True, help_text='Cualquier detalle o descripción adicional sobre el vehículo. Opcional.', verbose_name='descripción adicional'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='engine',
            field=models.CharField(blank=True, error_messages={'max_length': 'La descripción del motor no puede tener más de 30 caracteres.'}, help_text='Modelo o cilindrada del motor (ej. ‘2GR-FE’ o ‘1998 cc’). Máx. 30 caracteres. Opcional.', max_length=30, verbose_name='descripción del motor'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='engine_number',
            field=models.CharField(error_messages={'max_length': 'El número de motor no puede tener más de 17 caracteres.', 'required': 'El número de motor es obligatorio.', 'unique': 'Este número de motor ya está registrado.'}, help_text='Número de serie del motor (único, máx. 17 caracteres). Puede ser alfanumérico.', max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message='El número de motor solo debe contener letras mayúsculas y números.', regex='^[A-Z0-9]+$')], verbose_name='número de motor'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='engine_type',
            field=models.CharField(choices=[('Gasolina', 'Gasolina'), ('Diesel', 'Diesel'), ('Electrico', 'Eléctrico'), ('Hibrido', 'Híbrido'), ('GLP', 'GLP')], error_messages={'invalid_choice': 'El tipo de motor seleccionado no es una opción válida.', 'required': 'Debe seleccionar un tipo de motor.'}, help_text='Seleccione el tipo de motor.', max_length=10, verbose_name='tipo de motor'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='modified_by',
            field=models.IntegerField(blank=True, null=True, verbose_name='modificado por'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='plate',
            field=models.CharField(error_messages={'blank': 'La placa no puede estar vacía.', 'required': 'La placa es un campo obligatorio.', 'unique': 'Esta placa ya está registrada.'}, help_text='Placa única, sin espacios ni caracteres especiales, 6–8 caracteres (ej. ABC1234).', max_length=8, unique=True, validators=[django.core.validators.RegexValidator(message='La placa debe tener entre 6 y 8 caracteres alfanuméricos en mayúsculas (ej. ABC123D o ABC1234).', regex='^[A-Z0-9]{6,8}$')]),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='seat_count',
            field=models.PositiveIntegerField(error_messages={'invalid': 'Ingrese una cantidad de asientos válida.', 'required': 'La cantidad de asientos es obligatoria.'}, help_text='Número de asientos (incluyendo conductor), entre 1 y 50.', validators=[django.core.validators.MinValueValidator(1, message='La cantidad de asientos debe ser como mínimo 1.'), django.core.validators.MaxValueValidator(50, message='La cantidad de asientos no puede exceder los 50.')], verbose_name='cantidad de asientos'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('En mantenimiento', 'En mantenimiento'), ('En reparacion', 'En reparación'), ('Reservado', 'Reservado'), ('Alquilado', 'Alquilado')], default='Disponible', error_messages={'invalid_choice': 'El estado seleccionado no es una opción válida.', 'required': 'Debe seleccionar un estado para el vehículo.'}, help_text='Seleccione el estado actual del vehículo.', max_length=20, verbose_name='estado del vehículo'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='última modificación'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehiclecategory',
            field=models.ForeignKey(error_messages={'invalid_choice': 'La categoría de vehículo seleccionada no es válida.', 'required': 'Debe seleccionar una categoría de vehículo.'}, help_text='Seleccione la categoría del vehículo.', on_delete=django.db.models.deletion.RESTRICT, to='vehiclecategory.vehiclecategory', verbose_name='categoría del vehículo'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehiclemodel',
            field=models.ForeignKey(error_messages={'invalid_choice': 'El modelo de vehículo seleccionado no es válido.', 'required': 'Debe seleccionar un modelo de vehículo.'}, help_text='Seleccione el modelo del vehículo.', on_delete=django.db.models.deletion.RESTRICT, to='vehiclemodel.vehiclemodel', verbose_name='modelo del vehículo'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vin',
            field=models.CharField(error_messages={'max_length': 'El VIN debe tener exactamente 17 caracteres.', 'required': 'El VIN es obligatorio.', 'unique': 'Este VIN ya está registrado.'}, help_text='VIN único de 17 caracteres (sin I, O, Q).', max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message='VIN inválido: debe tener 17 caracteres alfanuméricos y no debe contener las letras I, O, Q.', regex='^[A-HJ-NPR-Z0-9]{17}$')], verbose_name='VIN (Número de Identificación Vehicular)'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='year',
            field=models.PositiveIntegerField(error_messages={'invalid': 'Ingrese un año válido.', 'required': 'El año de fabricación es obligatorio.'}, help_text='Año de fabricación del vehículo (ej. 2023).', validators=[django.core.validators.MinValueValidator(1886, message='El año de fabricación no puede ser anterior a 1886.'), django.core.validators.MaxValueValidator(vehicle.models.get_next_year, message='El año de fabricación no puede ser mayor al siguiente año del actual.')], verbose_name='año de fabricación'),
        ),
    ]
