# Generated by Django 5.2 on 2025-06-05 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0001_initial'),
        ('vehicle', '0004_alter_vehicle_options_alter_vehicle_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='branch',
            field=models.ForeignKey(default=1, error_messages={'blank': 'Debe seleccionar una sucursal para el vehículo.', 'invalid_choice': 'La sucursal seleccionada no es válida.', 'null': 'El vehículo debe estar asignado a una sucursal.', 'required': 'Debe asignar el vehículo a una sucursal.'}, help_text='Seleccione la sucursal donde se encuentra o a la que está asignado el vehículo.', on_delete=django.db.models.deletion.RESTRICT, to='branch.branch', verbose_name='sucursal asignada'),
            preserve_default=False,
        ),
    ]
