# Generated by Django 5.2 on 2025-06-04 20:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0001_initial'),
        ('vehiclemodel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiclemodel',
            options={'verbose_name': 'Modelo de Vehículo', 'verbose_name_plural': 'Modelos de Vehículos'},
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='active',
            field=models.BooleanField(default=True, verbose_name='activo'),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='brand',
            field=models.ForeignKey(error_messages={'blank': 'La marca no puede estar en blanco.', 'invalid_choice': 'La marca seleccionada no es válida.', 'null': 'La marca no puede estar vacía.', 'required': 'Debe seleccionar una marca.'}, help_text='Seleccione la marca del modelo del vehículo.', on_delete=django.db.models.deletion.RESTRICT, to='brand.brand', verbose_name='marca'),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación'),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='created_by',
            field=models.IntegerField(blank=True, null=True, verbose_name='creado por'),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='modified_by',
            field=models.IntegerField(blank=True, null=True, verbose_name='modificado por'),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='name',
            field=models.CharField(error_messages={'blank': 'El nombre del modelo no puede estar vacío.', 'max_length': 'El nombre del modelo no puede tener más de 100 caracteres.', 'required': 'El nombre del modelo es obligatorio.', 'unique': 'Ya existe un modelo con este nombre para esta marca.'}, help_text='Nombre del modelo del vehículo (ej. Corolla, Hilux, Civic). Máx. 100 caracteres.', max_length=100, validators=[django.core.validators.RegexValidator(message='El nombre del modelo solo puede contener letras, números, espacios, guiones (-) y puntos (.).', regex='^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚüÜ\\s\\-\\.]+$')], verbose_name='nombre del modelo'),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='última modificación'),
        ),
        migrations.AlterUniqueTogether(
            name='vehiclemodel',
            unique_together={('brand', 'name')},
        ),
    ]
