# Generated by Django 5.2 on 2025-06-07 16:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'required': 'El nombre de la categoría es obligatorio.', 'unique': 'Esta categoría ya se encuentra registrada.'}, help_text='Nombre único de la categoría del vehículo (máx. 50 caracteres).', max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='El nombre de la categoría solo puede contener letras, números, espacios y guiones.', regex='^[a-zA-Z0-9\\s\\-]+$')], verbose_name='nombre de la categoría')),
                ('active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_by', models.IntegerField(blank=True, null=True, verbose_name='creado por')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('modified_by', models.IntegerField(blank=True, null=True, verbose_name='modificado por')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última modificación')),
            ],
            options={
                'verbose_name': 'Categoría de Vehículo',
                'verbose_name_plural': 'Categorías de Vehículos',
                'db_table': 'vehiclecategory',
            },
        ),
    ]
