# Generated by Django 5.2 on 2025-06-06 00:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('district', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'blank': 'El nombre de la sucursal no puede estar vacío.', 'required': 'El nombre de la sucursal es obligatorio.', 'unique': 'Ya existe una sucursal con este nombre.'}, help_text='Nombre completo de la sucursal (máx. 100 caracteres).', max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message="El nombre solo puede contener letras, números, espacios y los siguientes caracteres: - . , # & ( ) '", regex="^[a-zA-Z0-9\\s\\-\\.,#&()\\'ñÑáéíóúÁÉÍÓÚ]+$")], verbose_name='nombre de la sucursal')),
                ('phone', models.CharField(error_messages={'blank': 'El número de teléfono no puede estar vacío.', 'required': 'El número de teléfono es obligatorio.'}, help_text='Número de teléfono principal de la sucursal (ej. +503 2222-1111).', max_length=25, validators=[django.core.validators.RegexValidator(message='Ingrese un número de teléfono válido (ej. +503 2222-1111). Puede incluir el código de país.', regex='^\\+?[0-9\\s\\-\\(\\)]{7,24}$')], verbose_name='teléfono de contacto')),
                ('address', models.TextField(error_messages={'blank': 'La dirección no puede estar vacía.', 'required': 'La dirección es obligatoria.'}, help_text='Dirección física detallada de la sucursal.', verbose_name='dirección completa')),
                ('email', models.EmailField(error_messages={'blank': 'El correo electrónico no puede estar vacío.', 'required': 'El correo electrónico es obligatorio.', 'unique': 'Esta dirección de correo electrónico ya está registrada.'}, help_text='Correo electrónico de contacto de la sucursal (debe ser único).', max_length=100, unique=True, validators=[django.core.validators.EmailValidator(message='Ingrese una dirección de correo electrónico válida.')], verbose_name='correo electrónico')),
                ('active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_by', models.IntegerField(blank=True, null=True, verbose_name='creado por')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('modified_by', models.IntegerField(blank=True, null=True, verbose_name='modificado por')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última modificación')),
                ('district', models.ForeignKey(error_messages={'blank': 'Debe seleccionar un distrito.', 'invalid_choice': 'El distrito seleccionado no es válido.', 'required': 'El distrito es obligatorio.'}, help_text='Seleccione el distrito donde se ubica la sucursal.', on_delete=django.db.models.deletion.RESTRICT, related_name='branches', to='district.district', verbose_name='distrito')),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
                'db_table': 'branch',
            },
        ),
    ]
