# Generated by Django 5.2 on 2025-05-14 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='created_by',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='modified_by',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
