# Generated by Django 5.2 on 2025-06-07 16:53

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, error_messages={'invalid': 'Ingrese un monto válido.', 'required': 'El monto es un campo obligatorio.'}, help_text='La cantidad de dinero pagada o reembolsada.', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='monto del pago')),
                ('payment_type', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Tarjeta de Crédito', 'Tarjeta de Crédito'), ('Tarjeta de Débito', 'Tarjeta de Débito'), ('Transferencia', 'Transferencia Bancaria')], error_messages={'required': 'Debe seleccionar un método de pago.'}, help_text='El método utilizado para realizar el pago.', max_length=20, verbose_name='método de pago')),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Momento exacto en que se realizó la transacción.', verbose_name='fecha y hora del pago')),
                ('concept', models.CharField(choices=[('Anticipo', 'Anticipo'), ('Pago Final', 'Pago Final'), ('Cargo Adicional', 'Cargo Adicional'), ('Cargo por Retraso', 'Cargo por Retraso'), ('Reembolso', 'Reembolso')], error_messages={'required': 'Debe especificar el concepto del pago.'}, help_text='La razón o motivo del pago (anticipo, pago final, etc.).', max_length=20, verbose_name='concepto del pago')),
                ('active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_by', models.IntegerField(blank=True, null=True, verbose_name='creado por')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('modified_by', models.IntegerField(blank=True, null=True, verbose_name='modificado por')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última modificación')),
                ('rental', models.ForeignKey(error_messages={'required': 'El pago debe estar asociado a un alquiler.'}, help_text='El alquiler al que corresponde este pago.', on_delete=django.db.models.deletion.CASCADE, to='rental.rental', verbose_name='alquiler asociado')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'payment',
            },
        ),
    ]
