# Generated by Django 5.2 on 2025-06-09 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='reference',
            field=models.CharField(blank=True, help_text='Información adicional (Depósito de seguridad para extranjero, 50% del costo del alquiler, etc.).', max_length=150, verbose_name='referencia o código de transacción'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('Efectivo', 'Efectivo'), ('Tarjeta de Credito', 'Tarjeta de Crédito'), ('Tarjeta de Debito', 'Tarjeta de Débito'), ('Transferencia', 'Transferencia Bancaria')], error_messages={'required': 'Debe seleccionar un método de pago.'}, help_text='El método utilizado para realizar el pago.', max_length=20, verbose_name='método de pago'),
        ),
    ]
