# Generated by Django 5.2 on 2025-06-09 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_payment_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('Efectivo', 'Efectivo'), ('Tarjeta de Credito', 'Tarjeta de Crédito'), ('Tarjeta de Debito', 'Tarjeta de Débito'), ('Transferencia', 'Transferencia Bancaria')], error_messages={'required': 'Debe seleccionar un método de pago.'}, help_text='El método utilizado para realizar el pago.', max_length=20, verbose_name='método de pago'),
        ),
    ]
