# Generated by Django 5.2 on 2025-06-07 16:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'required': 'El nombre de la marca es obligatorio.', 'unique': 'Esta marca ya se encuentra registrada.'}, help_text='Nombre único de la marca del vehículo (máx. 100 caracteres).', max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message="El nombre de la marca solo puede contener letras, números, espacios, guiones, '&' o '.'.", regex='^[a-zA-Z0-9\\s\\-&.]+$')], verbose_name='nombre de la marca')),
                ('active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_by', models.IntegerField(blank=True, null=True, verbose_name='creado por')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('modified_by', models.IntegerField(blank=True, null=True, verbose_name='modificado por')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última modificación')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'db_table': 'brand',
            },
        ),
    ]
