# Generated by Django 5.2 on 2025-06-10 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='reference',
            field=models.CharField(blank=True, help_text='Información adicional (Depósito de seguridad para extranjero, 50% del costo del alquiler, etc.).', max_length=150, verbose_name='referencia o código de transacción'),
        ),
    ]
